### PR TITLE
[Setup] Project setup

### PR DESCRIPTION
**Pull request by Onyimatics**
### What does this PR do?
- This PR contains the project setup

#### Description of Task to be completed?
- Setup the project and make it ready for team coding.

#### How should this be manually tested?
- Clone the repo [vote-right-frontend](https://github.com/Enye-Team-Giraffe/vote-right-frontend)
- cd `vote-right-frontend`
-  `npm install`
-  `npm run start` on your terminal

#### Checklist:
- [x] set ui framework(reactjs)
- [x] setup test environment(jest, enzyme)
- [x] setup code transpiler(babel)
- [x] setup code linter(ESLint)
- [x] setup continuous integration(Travisci)
- [x] add travisci badge

#### Stories?
- N/A

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

### CODE REVIEW

**Review by xand6r — COMMENTED** [review]
it is okay.

**Review by xand6r — COMMENTED** [review]
looks good

**Review by usmanoa — APPROVED** [review]

**Comment by xand6r** [comment]
Looks good

**Review by enyeInc — APPROVED** [review]
LGTM - Looks Good To Me

**Pull request merged**
